server:
  port: 8084
spring:
  application:
    name: Api-Gateway
    
  cloud:
    gateway:
      routes:
        - id: USERSERVICE2
          uri: lb://USERSERVICE2
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
            
            

        - id: RATINGSERVICE2
          uri: lb://RATINGSERVICE2
          predicates:
            - Path=/ratings/**
          filters:
            - AuthenticationFilter



        - id: HOTELSERVICE2
          uri: lb://HOTELSERVICE2
          predicates:
            - Path=/hotels/**
          filters:
            - AuthenticationFilter



        - id: Identity-Service
          uri: lb://Identity-Service
          predicates:
            - Path=/auth/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
      
      
      